#include QMK_KEYBOARD_H
#include "features/orbital_mouse.h"`


/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */


const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {

	[0] = LAYOUT_split_3x5_3(
					KC_Q, KC_W, KC_E, KC_R, KC_T,
						KC_Y, KC_U, KC_I, KC_O, KC_P,
					LGUI_T(KC_A), LALT_T(KC_S), LCTL_T(KC_D), LSFT_T(KC_F), KC_G,
						KC_H, RSFT_T(KC_J), LCTL_T(KC_K), LALT_T(KC_L), LGUI_T(KC_SCLN),
					KC_Z, KC_X, KC_C, KC_V, KC_B,
						KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH,
					LT(5,KC_ESC), LT(1,KC_SPC), LT(3,KC_TAB),
						LT(4,KC_DEL), LT(2,KC_BSPC), LT(6,KC_ENT)
					),
	
	
	// 1
	// nav - arrows, pgup/pgdn, and some symbols
	// left split, middle / space
	[1] = LAYOUT_split_3x5_3(
					KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
						KC_EQL, KC_HOME, KC_UP, KC_END, KC_GRV,
					KC_LGUI, KC_LCTL, KC_LALT, KC_LSFT, KC_NO,
						KC_MINS, KC_LEFT, KC_DOWN, KC_RIGHT, KC_PGUP,
					KC_NO, LCTL(KC_X), LCTL(KC_C), LCTL(KC_V), KC_NO,
						KC_QUOT, KC_BSLS, KC_LBRC, KC_RBRC, KC_PGDN,
					KC_NO, KC_NO, KC_NO,
						KC_NO, KC_NO, KC_NO), 
	// 2
	// top number row w shifted symbols
	// right split, middle / backspace
	[2] = LAYOUT_split_3x5_3(
					KC_1, KC_2, KC_3, KC_4, KC_5,
						KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
					KC_6, KC_7, KC_8, KC_9, KC_0,
						KC_NO, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
					KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
						KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, 
					KC_NO, KC_NO, KC_NO,
						KC_NO, KC_NO, KC_NO),
	// 3
	// symbols
	// left split, right / 	tab

	[3] = LAYOUT_split_3x5_3(
					KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
						KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
					KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_NO,
						KC_NO, KC_NO, OM_U, KC_NO, KC_NO,
					KC_NO, OM_L, OM_D, OM_R, OM_W_U, 
						KC_NO, KC_NO, KC_NO, KC_NO, OM_W_D,
					KC_NO, KC_NO, KC_NO,
						OM_SLOW, OM_BTN1, OM_BTN2),

	[4] = LAYOUT_split_3x5_3(
					KC_EQL, KC_CIRC, KC_LT, KC_GT, KC_SCLN,
						KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
					KC_LCBR, KC_RCBR, KC_LPRN, KC_RPRN, KC_AT,
						KC_NO, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
					KC_MINS, KC_EXLM, KC_LBRC, KC_RBRC, KC_TRNS,
						KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
					KC_NO, KC_NO, KC_NO,
						KC_NO, KC_NO, KC_NO),

	[5] = LAYOUT_split_3x5_3(
					RGB_SPI,	RGB_VAI, 	RGB_SAI, 	RGB_HUI, 	RGB_MOD,
								KC_PPLS,	KC_P7, 		KC_P8, 		KC_P9, 		KC_PAST,
							EE_CLR, 	KC_TRNS,	KC_TRNS, 	KC_TRNS, 	RGB_TOG,
								KC_PMNS, 	KC_P4, 		KC_P5,		KC_P6, 		KC_PSLS,
							RGB_SPD, 	RGB_VAD, 	RGB_SAD, 	RGB_HUD,	RGB_RMOD,
								KC_PDOT, 	KC_P1, 		KC_P2, 		KC_P3, 		KC_PEQL,
					KC_NO, KC_NO, KC_NO,
						KC_NO, KC_NO, KC_P0),

	[6] = LAYOUT_split_3x5_3(
					QK_RBT, KC_NO, KC_NO, KC_NO, KC_NO,
						KC_NO, KC_F7, KC_F8, KC_F9, KC_F10,
					KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,	KC_NO,
						KC_NO, KC_F4, KC_F5, KC_F6, KC_F11,
					KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
						KC_NO, KC_F1, KC_F2, KC_F3, KC_F12,
					KC_NO, KC_NO, KC_NO,
						KC_NO, KC_NO, KC_NO),
	

};

#if	defined(ENCODER_ENABLE)	&& defined(ENCODER_MAP_ENABLE)
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {

};
#endif // defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)

bool process_record_user(uint16_t keycode, keyrecord_t* record) {
	if (!process_orbital_mouse(keycode, record)) { return false; }
  
	// Your macros ...
	return true;
}
  
void housekeeping_task_user(void) {
	orbital_mouse_task();
  
	// Other tasks ...
}




